name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

    #  githubのsecretsに登録した値を.envとして使う
      - name: Set up .env
        run: echo 'VITE_AZURE_SEARCH_API_KEYL="${{ secrets.VITE_AZURE_SEARCH_API_KEY }}"' > ./front/.env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: cd front
        run: cd front
      - name: search env file
        run: ls -la

      - name: Build a docker image with commit SHA
        run: docker build -t mashikotyan/hackz:${{ github.sha }} -f ./docker/dockerfile .
      
      - name: Tag the image as latest
        run: docker tag mashikotyan/hackz:${{ github.sha }} mashikotyan/hackz:latest
      
      - name: Push the docker image with commit SHA
        run: docker push mashikotyan/hackz:${{ github.sha }}
      
      - name: Push the docker image with latest tag
        run: docker push mashikotyan/hackz:latest
      
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: hackz
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'registry.hub.docker.com/mashikotyan/hackz:${{ github.sha }}'