name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build a docker image with commit SHA
        run: docker build -t mashikotyan/hackz:${{ github.sha }} -f ./docker/dockerfile .
      
      - name: Tag the image as latest
        run: docker tag mashikotyan/hackz:${{ github.sha }} mashikotyan/hackz:latest
      
      - name: Push the docker image with commit SHA
        run: docker push mashikotyan/hackz:${{ github.sha }}
      
      - name: Push the docker image with latest tag
        run: docker push mashikotyan/hackz:latest